server:
  port: 8082
spring:
  application:
    name: micro-service-dubbo-saas
  dubbo:
    application:
      name: micro-service-dubbo-saas
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.steve.service
banner:
  charset: utf-8
  image:
    margin: 5
  location: classpath:config/banner.txt
logging:
  config: classpath:config/logback.xml